module.exports = {
    microbreakDuration: 20000,
    microbreakInterval: 60000,
    // microbreakInterval: 10000,
    // breakDuration: 300000,
    breakDuration: 30000,
    breakInterval: 30,
    breakNotification: true,
    microbreakNotification: true,
    // breakNotificationInterval: 30000,
    breakNotificationInterval: 0,
    microbreakNotificationInterval: 0,
    microbreak: false,
    break: true,
    microbreakStrictMode: false,
    breakStrictMode: false,
    morningHour: 6,
    microbreakPostpone: true,
    breakPostpone: true,
    microbreakPostponeTime: 120000,
    breakPostponeTime: 300000,
    microbreakPostponesLimit: 1,
    microbreakPostponableDurationPercent: 30,
    breakPostponesLimit: 1,
    breakPostponableDurationPercent: 30,
    mainColor: '#1D1F21',
    transparentMode: false,
    opacity: 0.9,
    audio: 'crystal-glass',
    volume: 1,
    fullscreen: true,
    ideas: true,
    naturalBreaks: true,
    naturalBreaksInactivityResetTime: 300000,
    allScreens: true,
    useIdeasFromSettings: false,
    language: 'en',
    notifyNewVersion: true,
    isFirstRun: true,
    posLatitude: 0.0,
    posLongitude: 0.0,
    useMonochromeTrayIcon: false,
    useMonochromeInvertedTrayIcon: false,
    silentNotifications: false,
    monitorDnd: true,
    microbreakStartSoundPlaying: false,
    breakStartSoundPlaying: false,
    themeSource: 'system',
    endBreakShortcut: 'CmdOrCtrl+X',
    breakWindowWidth: 0.85,
    breakWindowHeight: 0.85,
    moodQuestionInterval: 12 * 60 * 60 * 1000,
    notificationDuration: 10000
}